version: 2
updates:
  # Go module dependencies
  - package-ecosystem: "gomod"
    directory: "/tinygo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "pulseengine/maintainers"
    assignees:
      - "pulseengine/maintainers"
    commit-message:
      prefix: "go"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "automated"

  # Rust dependencies (if Rust implementation exists)
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "pulseengine/maintainers"
    assignees:
      - "pulseengine/maintainers"
    commit-message:
      prefix: "rust"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
      - "automated"

  # NPM dependencies for documentation site
  - package-ecosystem: "npm"
    directory: "/docs-site"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "pulseengine/maintainers"
    commit-message:
      prefix: "docs"
      include: "scope"
    labels:
      - "dependencies"
      - "documentation"
      - "automated"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "pulseengine/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "ci-cd"
      - "automated"
